version: "3"
services:
  golden-bag-backend_a:
    build: .
    working_dir: /app
    volumes:
      - ~/.m2:/root/.m2
    expose:
      - "8080"
#   command: mvn clean spring-boot:run -Dspring.profiles.active=docker
    command: mvn clean spring-boot:run
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - app_net

networks:
  app_net:
    external:
      name: app_net
